# Generated by Django 4.1.2 on 2022-10-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('detil', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
